
ALTER TABLE events ADD COLUMN IF NOT EXISTS detailed_description CLOB;
ALTER TABLE events ADD COLUMN IF NOT EXISTS agenda VARCHAR(255);
ALTER TABLE events ADD COLUMN IF NOT EXISTS speakers VARCHAR(255);
ALTER TABLE events ADD COLUMN IF NOT EXISTS dress_code VARCHAR(100);